import type { SolicitacaoOS } from '../tipos/ordemServico'

export const SOLICITACOES_MOCK: SolicitacaoOS[] = [
  {
    id: 1,
    maquinaNome: 'Torno CNC 01',
    maquinaCodigo: 'MAQ-001',
    status: 'Pendente',
    descricao: 'Falha no eixo X, travamento durante operação.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-17T08:32:00',
  },
  {
    id: 2,
    maquinaNome: 'Prensa Hidráulica 04',
    maquinaCodigo: 'MAQ-004',
    status: 'Convertida',
    descricao: 'Vazamento de óleo hidráulico na mangueira principal.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-16T14:15:00',
  },
  {
    id: 3,
    maquinaNome: 'Fresadora 02',
    maquinaCodigo: 'MAQ-002',
    status: 'Rejeitada',
    descricao: 'Ruído anormal no cabeçote durante fresamento.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-15T09:50:00',
  },
  {
    id: 4,
    maquinaNome: 'Injetora de Plástico 06',
    maquinaCodigo: 'MAQ-006',
    status: 'Pendente',
    descricao: 'Temperatura de injeção fora do padrão esperado.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-14T11:20:00',
  },
  {
    id: 5,
    maquinaNome: 'Compressor Atlas 03',
    maquinaCodigo: 'MAQ-003',
    status: 'Convertida',
    descricao: 'Pressão caindo abaixo de 6 bar em operação contínua.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-12T16:05:00',
  },
  {
    id: 6,
    maquinaNome: 'Retífica Plana 07',
    maquinaCodigo: 'MAQ-007',
    status: 'Convertida',
    descricao: 'Rebolo desbalanceado, vibração excessiva na mesa.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-10T07:45:00',
  },
  {
    id: 7,
    maquinaNome: 'Solda MIG 08',
    maquinaCodigo: 'MAQ-008',
    status: 'Pendente',
    descricao: 'Arco elétrico instável durante a soldagem.',
    solicitante: 'Marina',
    criadoEm: '2026-07-09T13:10:00',
  },
  {
    id: 8,
    maquinaNome: 'Esteira Transportadora 09',
    maquinaCodigo: 'MAQ-009',
    status: 'Rejeitada',
    descricao: 'Correia desalinhada causando parada intermitente.',
    solicitante: 'Marina',
    criadoEm: '2026-07-08T10:30:00',
  },
  {
    id: 9,
    maquinaNome: 'Empilhadeira Elétrica 10',
    maquinaCodigo: 'MAQ-010',
    status: 'Convertida',
    descricao: 'Bateria não segura carga por mais de 2 horas.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-07T15:40:00',
  },
  {
    id: 10,
    maquinaNome: 'Balança Industrial 11',
    maquinaCodigo: 'MAQ-011',
    status: 'Pendente',
    descricao: 'Leitura de peso divergente entre medições.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-06T09:00:00',
  },
  {
    id: 11,
    maquinaNome: 'Seladora a Vácuo 12',
    maquinaCodigo: 'MAQ-012',
    status: 'Convertida',
    descricao: 'Vedação não fechando corretamente as embalagens.',
    solicitante: 'Marina',
    criadoEm: '2026-07-05T12:25:00',
  },
  {
    id: 12,
    maquinaNome: 'Torno CNC 05',
    maquinaCodigo: 'MAQ-005',
    status: 'Pendente',
    descricao: 'Alarme de sobrecarga no motor principal.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-04T08:15:00',
  },
  {
    id: 13,
    maquinaNome: 'Compressor Atlas 13',
    maquinaCodigo: 'MAQ-013',
    status: 'Rejeitada',
    descricao: 'Ruído excessivo identificado como desgaste natural.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-03T17:00:00',
  },
  {
    id: 14,
    maquinaNome: 'Robô Soldador 14',
    maquinaCodigo: 'MAQ-014',
    status: 'Convertida',
    descricao: 'Erro de calibração nos eixos de movimento.',
    solicitante: 'Marina',
    criadoEm: '2026-07-02T14:50:00',
  },
  {
    id: 15,
    maquinaNome: 'Etiquetadora Automática 15',
    maquinaCodigo: 'MAQ-015',
    status: 'Pendente',
    descricao: 'Sensor de posicionamento não detecta as caixas.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-01T11:35:00',
  },
  {
    id: 16,
    maquinaNome: 'Prensa Hidráulica 16',
    maquinaCodigo: 'MAQ-016',
    status: 'Convertida',
    descricao: 'Cilindro hidráulico com perda de força.',
    solicitante: 'Eduardo',
    criadoEm: '2026-06-30T09:20:00',
  },
  {
    id: 17,
    maquinaNome: 'Fresadora 17',
    maquinaCodigo: 'MAQ-017',
    status: 'Pendente',
    descricao: 'Vibração excessiva no cabeçote de corte.',
    solicitante: 'Marina',
    criadoEm: '2026-06-29T16:10:00',
  },
  {
    id: 18,
    maquinaNome: 'Compressor Atlas 18',
    maquinaCodigo: 'MAQ-018',
    status: 'Convertida',
    descricao: 'Superaquecimento identificado no compressor.',
    solicitante: 'Carlos',
    criadoEm: '2026-06-28T10:05:00',
  },
]
