import type { SolicitacaoOS } from '../tipos/ordemServico'

export const SOLICITACOES_MOCK: SolicitacaoOS[] = [
  {
    id: 1,
    maquinaNome: 'Forno Industrial de Pão',
    maquinaCodigo: 'MAQ-001',
    status: 'Pendente',
    descricao: 'Termostato não atinge a temperatura programada.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-17T08:32:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
  },
  {
    id: 2,
    maquinaNome: 'Câmara Fria de Carnes',
    maquinaCodigo: 'MAQ-004',
    status: 'Convertida',
    descricao: 'Câmara não está mantendo a temperatura mínima exigida.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-16T14:15:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
  },
  {
    id: 3,
    maquinaNome: 'Masseira Industrial',
    maquinaCodigo: 'MAQ-002',
    status: 'Rejeitada',
    descricao: 'Motor com ruído excessivo durante o amassamento.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-15T09:50:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
  },
  {
    id: 4,
    maquinaNome: 'Câmara Fria de Hortifruti',
    maquinaCodigo: 'MAQ-006',
    status: 'Pendente',
    descricao: 'Vedação da porta comprometida, perda de refrigeração.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-14T11:20:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
  },
  {
    id: 5,
    maquinaNome: 'Serra Fita para Carnes',
    maquinaCodigo: 'MAQ-003',
    status: 'Convertida',
    descricao: 'Lâmina desalinhada causando corte irregular.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-12T16:05:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
  },
  {
    id: 6,
    maquinaNome: 'Balança Eletrônica de Pesagem',
    maquinaCodigo: 'MAQ-007',
    status: 'Convertida',
    descricao: 'Leitura de peso divergente entre pesagens.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-10T07:45:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
  },
  {
    id: 7,
    maquinaNome: 'Embaladora a Vácuo',
    maquinaCodigo: 'MAQ-005',
    status: 'Pendente',
    descricao: 'Selagem das embalagens não está vedando corretamente.',
    solicitante: 'Marina',
    criadoEm: '2026-07-09T13:10:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
  },
  {
    id: 8,
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    status: 'Rejeitada',
    descricao: 'Temperatura do balcão subindo acima do permitido.',
    solicitante: 'Marina',
    criadoEm: '2026-07-08T10:30:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
  },
  {
    id: 9,
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    status: 'Convertida',
    descricao: 'Compressor apresentando falha intermitente.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-07T15:40:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
  },
  {
    id: 10,
    maquinaNome: 'Fatiadora de Frios',
    maquinaCodigo: 'MAQ-011',
    status: 'Pendente',
    descricao: 'Lâmina não corta uniformemente, deixando fatias grossas.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-06T09:00:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
  },
  {
    id: 11,
    maquinaNome: 'Sistema de Refrigeração de Bebidas',
    maquinaCodigo: 'MAQ-014',
    status: 'Convertida',
    descricao: 'Bebidas não estão gelando adequadamente.',
    solicitante: 'Marina',
    criadoEm: '2026-07-05T12:25:00',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
  },
  {
    id: 12,
    maquinaNome: 'Balcão Refrigerado de Peixaria',
    maquinaCodigo: 'MAQ-008',
    status: 'Pendente',
    descricao: 'Gelo derretendo rápido demais, produto exposto.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-04T08:15:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
  },
  {
    id: 13,
    maquinaNome: 'Máquina de Gelo em Escamas',
    maquinaCodigo: 'MAQ-009',
    status: 'Rejeitada',
    descricao: 'Produção de gelo abaixo do volume necessário.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-03T17:00:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
  },
  {
    id: 14,
    maquinaNome: 'Empilhadeira Elétrica',
    maquinaCodigo: 'MAQ-013',
    status: 'Convertida',
    descricao: 'Bateria não segura carga por mais de 2 horas.',
    solicitante: 'Marina',
    criadoEm: '2026-07-02T14:50:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
  },
  {
    id: 15,
    maquinaNome: 'Ar Condicionado Central do Salão',
    maquinaCodigo: 'MAQ-015',
    status: 'Pendente',
    descricao: 'Climatização insuficiente no salão de vendas.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-01T11:35:00',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
  },
  {
    id: 16,
    maquinaNome: 'Forno Industrial de Pão',
    maquinaCodigo: 'MAQ-001',
    status: 'Convertida',
    descricao: 'Alarme de sobreaquecimento disparando sem motivo aparente.',
    solicitante: 'Eduardo',
    criadoEm: '2026-06-30T09:20:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
  },
  {
    id: 17,
    maquinaNome: 'Câmara Fria de Hortifruti',
    maquinaCodigo: 'MAQ-006',
    status: 'Pendente',
    descricao: 'Painel de controle travando ao configurar a temperatura.',
    solicitante: 'Marina',
    criadoEm: '2026-06-29T16:10:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
  },
  {
    id: 18,
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    status: 'Convertida',
    descricao: 'Ruído excessivo no compressor do balcão.',
    solicitante: 'Carlos',
    criadoEm: '2026-06-28T10:05:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
  },
]
