import type { SolicitacaoOS } from '../tipos/ordemServico'

// Fotos de exemplo (PNG minúsculo em base64) para as Solicitações OS mockadas — os dados
// de demonstração originais foram escritos antes da Foto do Defeito existir (ver item 3
// do CLAUDE.md), então precisam de uma foto "de mentira" pra exibir o recurso sem
// depender de o Solicitante enviar uma solicitação nova a cada demo.
const FOTO_MOCK_FERRUGEM =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAj0lEQVR42u3QQQ0AAAgEoOtjIytZ2hbOBxsJyHRxIApEi0a0aNEWRItGtGjRFkSLRrRo0YgWjWjRohEtGtGiRSNaNKJFi0a0aESLFo1o0YgWLRrRohEtWjSiRSNatGhEi0a0aNGIFo1o0aIRLRrRokUjWjSiRYtGtGhEixaNaNGIFi0a0aIRLVo0okUj+osFdMrVlaO98W8AAAAASUVORK5CYII='
const FOTO_MOCK_FUMACA =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAjklEQVR42u3QMQ0AAAgDsOncg38XuCAcTaqgaYcDUSBaNKJFi7YgWjSiRYu2IFo0okWLRrRoRIsWjWjRiBYtGtGiES1aNKJFI1q0aESLRrRo0YgWjWjRohEtGtGiRSNaNKJFi0a0aESLFo1o0YgWLRrRohEtWjSiRSNatGhEi0a0aNGIFo1o0aIRLRrRXyztWlQ0opCvyAAAAABJRU5ErkJggg=='
const FOTO_MOCK_VAZAMENTO =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAj0lEQVR42u3QQQ0AAAgEoAtmJjMZ1RbOBxsJSPVwIApEi0a0aNEWRItGtGjRFkSLRrRo0YgWjWjRohEtGtGiRSNaNKJFi0a0aESLFo1o0YgWLRrRohEtWjSiRSNatGhEi0a0aNGIFo1o0aIRLRrRokUjWjSiRYtGtGhEixaNaNGIFi0a0aIRLVo0okUj+osFHo9lC4U8fRQAAAAASUVORK5CYII='
const FOTO_MOCK_FAISCA =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAj0lEQVR42u3QQQ0AAAgEoItjYjMZyxbOBxsJyHRxIApEi0a0aNEWRItGtGjRFkSLRrRo0YgWjWjRohEtGtGiRSNaNKJFi0a0aESLFo1o0YgWLRrRohEtWjSiRSNatGhEi0a0aNGIFo1o0aIRLRrRokUjWjSiRYtGtGhEixaNaNGIFi0a0aIRLVo0okUj+osFW95I4dA4NsgAAAAASUVORK5CYII='
const FOTO_MOCK_TRINCA =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAjUlEQVR42u3QMQ0AAAgDsMmZROTjgnA0qYJmWg5EgWjRiBYt2oJo0YgWLdqCaNGIFi0a0aIRLVo0okUjWrRoRItGtGjRiBaNaNGiES0a0aJFI1o0okWLRrRoRIsWjWjRiBYtGtGiES1aNKJFI1q0aESLRrRo0YgWjWjRohEtGtGiRSNaNKJFi0a0aER/sfWI92Fc7eUiAAAAAElFTkSuQmCC'
const FOTO_MOCK_GELO =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAkElEQVR42u3QQQ0AAAgEoOsfxTg2sIktnA82EpDq4UAUiBaNaNGiLYgWjWjRoi2IFo1o0aIRLRrRokUjWjSiRYtGtGhEixaNaNGIFi0a0aIRLVo0okUjWrRoRItGtGjRiBaNaNGiES0a0aJFI1o0okWLRrRoRIsWjWjRiBYtGtGiES1aNKJFI1q0aESLRvQXC8rXuT4larbOAAAAAElFTkSuQmCC'
const FOTO_MOCK_VIDRO =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAkElEQVR42u3QMQ0AAAgDsPlXgwhePOGCcDSpgqZ6OBAFokUjWrRoC6JFI1q0aAuiRSNatGhEi0a0aNGIFo1o0aIRLRrRokUjWjSiRYtGtGhEixaNaNGIFi0a0aIRLVo0okUjWrRoRItGtGjRiBaNaNGiES0a0aJFI1o0okWLRrRoRIsWjWjRiBYtGtGiEf3FAkyiG8L0j69UAAAAAElFTkSuQmCC'
const FOTO_MOCK_HIDRAULICO =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABaCAIAAAD8YgW4AAAAj0lEQVR42u3QMQ0AAAgDsClBLDeicUE4mlRBUz0ciALRohEtWrQF0aIRLVq0BdGiES1aNKJFI1q0aESLRrRo0YgWjWjRohEtGtGiRSNaNKJFi0a0aESLFo1o0YgWLRrRohEtWjSiRSNatGhEi0a0aNGIFo1o0aIRLRrRokUjWjSiRYtGtGhEixaNaNGI/mIBR4xzILNs88sAAAAASUVORK5CYII='

export const SOLICITACOES_MOCK: SolicitacaoOS[] = [
  {
    id: 1,
    tipo: 'maquinario',
    maquinaNome: 'Forno Industrial de Pão',
    maquinaCodigo: 'MAQ-001',
    status: 'Pendente',
    descricao: 'Termostato não atinge a temperatura programada.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-17T08:32:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FERRUGEM,
  },
  {
    id: 2,
    tipo: 'maquinario',
    maquinaNome: 'Câmara Fria de Carnes',
    maquinaCodigo: 'MAQ-004',
    status: 'Convertida',
    descricao: 'Câmara não está mantendo a temperatura mínima exigida.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-16T14:15:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
    impactos: ['Afeta Produção', 'Parada Parcial'],
    origem: 'solicitante',
  },
  {
    id: 3,
    tipo: 'maquinario',
    maquinaNome: 'Masseira Industrial',
    maquinaCodigo: 'MAQ-002',
    status: 'Rejeitada',
    descricao: 'Motor com ruído excessivo durante o amassamento.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-15T09:50:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
  },
  {
    id: 4,
    tipo: 'maquinario',
    maquinaNome: 'Câmara Fria de Hortifruti',
    maquinaCodigo: 'MAQ-006',
    status: 'Pendente',
    descricao: 'Vedação da porta comprometida, perda de refrigeração.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-14T11:20:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_VAZAMENTO,
  },
  {
    id: 5,
    tipo: 'maquinario',
    maquinaNome: 'Serra Fita para Carnes',
    maquinaCodigo: 'MAQ-003',
    status: 'Convertida',
    descricao: 'Lâmina desalinhada causando corte irregular.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-12T16:05:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
  },
  {
    id: 6,
    tipo: 'maquinario',
    maquinaNome: 'Balança Eletrônica de Pesagem',
    maquinaCodigo: 'MAQ-007',
    status: 'Convertida',
    descricao: 'Leitura de peso divergente entre pesagens.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-10T07:45:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
  },
  {
    id: 7,
    tipo: 'maquinario',
    maquinaNome: 'Embaladora a Vácuo',
    maquinaCodigo: 'MAQ-005',
    status: 'Pendente',
    descricao: 'Selagem das embalagens não está vedando corretamente.',
    solicitante: 'Marina',
    criadoEm: '2026-07-09T13:10:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FAISCA,
  },
  {
    id: 8,
    tipo: 'maquinario',
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    status: 'Rejeitada',
    descricao: 'Temperatura do balcão subindo acima do permitido.',
    solicitante: 'Marina',
    criadoEm: '2026-07-08T10:30:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
  },
  {
    id: 9,
    tipo: 'maquinario',
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    status: 'Convertida',
    descricao: 'Compressor apresentando falha intermitente.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-07T15:40:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
  },
  {
    id: 10,
    tipo: 'maquinario',
    maquinaNome: 'Fatiadora de Frios',
    maquinaCodigo: 'MAQ-011',
    status: 'Pendente',
    descricao: 'Lâmina não corta uniformemente, deixando fatias grossas.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-06T09:00:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_TRINCA,
  },
  {
    id: 11,
    tipo: 'maquinario',
    maquinaNome: 'Sistema de Refrigeração de Bebidas',
    maquinaCodigo: 'MAQ-014',
    status: 'Convertida',
    descricao: 'Bebidas não estão gelando adequadamente.',
    solicitante: 'Marina',
    criadoEm: '2026-07-05T12:25:00',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
  },
  {
    id: 12,
    tipo: 'maquinario',
    maquinaNome: 'Balcão Refrigerado de Peixaria',
    maquinaCodigo: 'MAQ-008',
    status: 'Pendente',
    descricao: 'Gelo derretendo rápido demais, produto exposto.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-04T08:15:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_GELO,
  },
  {
    id: 13,
    tipo: 'maquinario',
    maquinaNome: 'Máquina de Gelo em Escamas',
    maquinaCodigo: 'MAQ-009',
    status: 'Rejeitada',
    descricao: 'Produção de gelo abaixo do volume necessário.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-03T17:00:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
  },
  {
    id: 14,
    tipo: 'maquinario',
    maquinaNome: 'Empilhadeira Elétrica',
    maquinaCodigo: 'MAQ-013',
    status: 'Convertida',
    descricao: 'Bateria não segura carga por mais de 2 horas.',
    solicitante: 'Marina',
    criadoEm: '2026-07-02T14:50:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
  },
  {
    id: 15,
    tipo: 'maquinario',
    maquinaNome: 'Ar Condicionado Central do Salão',
    maquinaCodigo: 'MAQ-015',
    status: 'Pendente',
    descricao: 'Climatização insuficiente no salão de vendas.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-01T11:35:00',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FUMACA,
  },
  {
    id: 16,
    tipo: 'maquinario',
    maquinaNome: 'Forno Industrial de Pão',
    maquinaCodigo: 'MAQ-001',
    status: 'Convertida',
    descricao: 'Alarme de sobreaquecimento disparando sem motivo aparente.',
    solicitante: 'Eduardo',
    criadoEm: '2026-06-30T09:20:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
    impactos: [],
    origem: 'solicitante',
  },
  {
    id: 17,
    tipo: 'maquinario',
    maquinaNome: 'Câmara Fria de Hortifruti',
    maquinaCodigo: 'MAQ-006',
    status: 'Pendente',
    descricao: 'Painel de controle travando ao configurar a temperatura.',
    solicitante: 'Marina',
    criadoEm: '2026-06-29T16:10:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
  },
  {
    id: 18,
    tipo: 'maquinario',
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    status: 'Convertida',
    descricao: 'Ruído excessivo no compressor do balcão.',
    solicitante: 'Carlos',
    criadoEm: '2026-06-28T10:05:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    impactos: [],
    origem: 'solicitante',
  },
  // Pequenos Reparos e OS Terceiros pendentes de aprovação — cobrindo os escopos dos
  // três gestores mockados (gestor1: Loja 1/Padaria+Açougue; gestor2: Loja 1/Hortifruti
  // +Peixaria; regional: Loja 2 e Loja 3 inteiras).
  {
    id: 19,
    tipo: 'reparo',
    maquinaNome: 'Lâmpada de LED - Depósito da Padaria',
    maquinaCodigo: '—',
    status: 'Pendente',
    descricao: 'Lâmpada queimada no depósito de farinha, área com iluminação insuficiente para conferência de estoque.',
    solicitante: 'Eduardo',
    criadoEm: '2026-08-03T08:10:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
    impactos: [],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FUMACA,
  },
  {
    id: 20,
    tipo: 'terceiros',
    maquinaNome: 'Serra Fita para Carnes',
    maquinaCodigo: 'MAQ-003',
    tipoDefeito: 'Mecânico',
    status: 'Pendente',
    descricao: 'Motor com ruído excessivo e superaquecimento constante, necessita revisão especializada do fabricante.',
    solicitante: 'Eduardo',
    criadoEm: '2026-08-03T09:40:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FERRUGEM,
  },
  {
    id: 21,
    tipo: 'reparo',
    maquinaNome: 'Piso da Câmara de Hortifruti',
    maquinaCodigo: '—',
    status: 'Pendente',
    descricao: 'Piso rachado na entrada da câmara de hortifruti, risco de escorregão para os funcionários.',
    solicitante: 'Marina',
    criadoEm: '2026-08-02T14:20:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_TRINCA,
  },
  {
    id: 22,
    tipo: 'terceiros',
    maquinaNome: 'Balcão Refrigerado de Peixaria',
    maquinaCodigo: 'MAQ-008',
    tipoDefeito: 'Elétrico',
    status: 'Pendente',
    descricao: 'Painel elétrico do balcão desarmando sozinho, necessita assistência técnica especializada em refrigeração.',
    solicitante: 'Eduardo',
    criadoEm: '2026-08-02T16:05:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    impactos: ['Afeta Produção', 'Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FAISCA,
  },
  {
    id: 23,
    tipo: 'reparo',
    maquinaNome: 'Vidro da Vitrine Frontal',
    maquinaCodigo: '—',
    status: 'Pendente',
    descricao: 'Vidro trincado na vitrine frontal da loja, próximo à entrada principal.',
    solicitante: 'Carlos',
    criadoEm: '2026-08-01T10:50:00',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
    impactos: [],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_VIDRO,
  },
  {
    id: 24,
    tipo: 'terceiros',
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    tipoDefeito: 'Hidráulico',
    status: 'Pendente',
    descricao: 'Vazamento no sistema de refrigeração da câmara, necessita técnico certificado em gás refrigerante.',
    solicitante: 'Marina',
    criadoEm: '2026-08-01T13:15:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_HIDRAULICO,
  },
  // Solicitações de origem das OS já em execução/finalizadas mockadas em
  // dadosMockOrdensServico.ts (ids 209-212 de Maquinário e 301-309 de Reparo/Terceiros)
  // — sem esses registros, o botão "Ver Solicitação Original" do Painel do Técnico
  // (que resolve a SolicitacaoOS pelo `solicitacaoId` da OrdemServico) não encontrava
  // a solicitação e caía no estado de erro para boa parte das OS mockadas.
  {
    id: 209,
    tipo: 'maquinario',
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    status: 'Convertida',
    descricao: 'Vedação da porta da câmara comprometida, perdendo refrigeração.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-14T08:00:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_VAZAMENTO,
  },
  {
    id: 210,
    tipo: 'maquinario',
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    status: 'Convertida',
    descricao: 'Motor do balcão emitindo cheiro de queimado.',
    solicitante: 'Carlos',
    criadoEm: '2026-08-02T15:00:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FUMACA,
  },
  {
    id: 211,
    tipo: 'maquinario',
    maquinaNome: 'Empilhadeira Elétrica',
    maquinaCodigo: 'MAQ-013',
    status: 'Convertida',
    descricao: 'Empilhadeira apresentando folga excessiva no garfo de elevação.',
    solicitante: 'Marina',
    criadoEm: '2026-07-31T16:10:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: [],
    origem: 'solicitante',
  },
  {
    id: 212,
    tipo: 'maquinario',
    maquinaNome: 'Fatiadora de Frios',
    maquinaCodigo: 'MAQ-011',
    status: 'Convertida',
    descricao: 'Lâmina soltando durante o corte, risco de segurança.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-05T08:30:00',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    impactos: ['Retrabalho'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FERRUGEM,
  },
  {
    id: 301,
    tipo: 'reparo',
    maquinaNome: 'Lâmpada de LED - Área de Fornos',
    maquinaCodigo: '—',
    status: 'Convertida',
    descricao:
      'Lâmpada queimada na área dos fornos, dificultando a checagem visual do ponto de assamento.',
    solicitante: 'Eduardo',
    criadoEm: '2026-08-03T08:40:00',
    setor: 'Padaria',
    lojaId: 'loja-1',
    impactos: [],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FUMACA,
  },
  {
    id: 302,
    tipo: 'reparo',
    maquinaNome: 'Porta da Câmara Fria de Carnes',
    maquinaCodigo: '—',
    status: 'Convertida',
    descricao: 'Dobradiça da porta da câmara fria solta, porta não fecha corretamente.',
    solicitante: 'Eduardo',
    criadoEm: '2026-08-02T09:15:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_VAZAMENTO,
  },
  {
    id: 303,
    tipo: 'reparo',
    maquinaNome: 'Piso da Câmara de Hortifruti',
    maquinaCodigo: '—',
    status: 'Convertida',
    descricao: 'Piso rachado na entrada da câmara de hortifruti, risco de escorregão.',
    solicitante: 'Marina',
    criadoEm: '2026-08-01T14:30:00',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    impactos: [],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_TRINCA,
  },
  {
    id: 304,
    tipo: 'reparo',
    maquinaNome: 'Torneira do Lavabo da Peixaria',
    maquinaCodigo: '—',
    status: 'Convertida',
    descricao:
      'Torneira vazando continuamente, desperdício de água na área de higienização.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-30T08:00:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    impactos: [],
    origem: 'solicitante',
  },
  {
    id: 305,
    tipo: 'reparo',
    maquinaNome: 'Prateleira de Aço do Estoque',
    maquinaCodigo: '—',
    status: 'Convertida',
    descricao: 'Prateleira com estrutura comprometida, risco de queda de mercadorias.',
    solicitante: 'Carlos',
    criadoEm: '2026-07-22T09:00:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FERRUGEM,
  },
  {
    id: 306,
    tipo: 'terceiros',
    maquinaNome: 'Serra Fita para Carnes',
    maquinaCodigo: 'MAQ-003',
    tipoDefeito: 'Mecânico',
    status: 'Convertida',
    descricao:
      'Motor com ruído excessivo e superaquecimento constante, necessita revisão especializada do fabricante.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-31T11:00:00',
    setor: 'Açougue',
    lojaId: 'loja-1',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FUMACA,
  },
  {
    id: 307,
    tipo: 'terceiros',
    maquinaNome: 'Balcão Refrigerado de Peixaria',
    maquinaCodigo: 'MAQ-008',
    tipoDefeito: 'Elétrico',
    status: 'Convertida',
    descricao:
      'Painel elétrico do balcão desarmando sozinho, necessita assistência técnica especializada em refrigeração.',
    solicitante: 'Eduardo',
    criadoEm: '2026-07-24T13:20:00',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_FAISCA,
  },
  {
    id: 308,
    tipo: 'terceiros',
    maquinaNome: 'Sistema de Refrigeração de Bebidas',
    maquinaCodigo: 'MAQ-014',
    tipoDefeito: 'Hidráulico',
    status: 'Convertida',
    descricao:
      'Sistema de refrigeração com vazamento de gás, requer técnico certificado em gás refrigerante.',
    solicitante: 'Carlos',
    criadoEm: '2026-08-01T15:45:00',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
    impactos: ['Parada Parcial'],
    origem: 'solicitante',
  },
  {
    id: 309,
    tipo: 'terceiros',
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    tipoDefeito: 'Hidráulico',
    status: 'Convertida',
    descricao:
      'Vazamento no sistema de refrigeração da câmara, necessitou técnico certificado em gás refrigerante.',
    solicitante: 'Marina',
    criadoEm: '2026-07-20T10:10:00',
    setor: 'Estoque',
    lojaId: 'loja-2',
    impactos: ['Afeta Produção'],
    origem: 'solicitante',
    fotoUrl: FOTO_MOCK_VAZAMENTO,
  },
]

let proximoId = Math.max(...SOLICITACOES_MOCK.map((item) => item.id)) + 1

// Centraliza a geração de id para as novas Solicitações OS (Reparo, Terceiros e,
// futuramente, Maquinário) — evita colisão de id entre os diferentes serviços que
// empurram registros para o mesmo SOLICITACOES_MOCK.
export function gerarProximoIdSolicitacao(): number {
  return proximoId++
}
