import type { PreventivaListada } from '../tipos/maquina'

export const PREVENTIVAS_MOCK: PreventivaListada[] = [
  {
    id: 'PREV-001',
    maquinaId: 'MAQ-001',
    maquinaNome: 'Forno Industrial de Pão',
    setor: 'Padaria',
    lojaId: 'loja-1',
    descricao: 'Limpeza e calibração do termostato.',
    intervaloDias: 30,
    proximaData: '2026-08-10',
    ativa: true,
  },
  {
    id: 'PREV-002',
    maquinaId: 'MAQ-002',
    maquinaNome: 'Masseira Industrial',
    setor: 'Padaria',
    lojaId: 'loja-1',
    descricao: 'Lubrificação dos rolamentos do motor.',
    intervaloDias: 60,
    proximaData: '2026-08-20',
    ativa: true,
  },
  {
    id: 'PREV-003',
    maquinaId: 'MAQ-003',
    maquinaNome: 'Serra Fita para Carnes',
    setor: 'Açougue',
    lojaId: 'loja-1',
    descricao: 'Afiação e troca da lâmina.',
    intervaloDias: 15,
    proximaData: '2026-08-05',
    ativa: true,
  },
  {
    id: 'PREV-004',
    maquinaId: 'MAQ-004',
    maquinaNome: 'Câmara Fria de Carnes',
    setor: 'Açougue',
    lojaId: 'loja-1',
    descricao: 'Verificação da vedação das portas e do gás refrigerante.',
    intervaloDias: 45,
    proximaData: '2026-08-15',
    ativa: false,
  },
  {
    id: 'PREV-005',
    maquinaId: 'MAQ-010',
    maquinaNome: 'Balcão Refrigerado de Frios',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    descricao: 'Higienização interna e checagem da temperatura.',
    intervaloDias: 30,
    proximaData: '2026-08-08',
    ativa: true,
  },
  {
    id: 'PREV-006',
    maquinaId: 'MAQ-013',
    maquinaNome: 'Empilhadeira Elétrica',
    setor: 'Estoque',
    lojaId: 'loja-2',
    descricao: 'Revisão da bateria e dos freios.',
    intervaloDias: 90,
    proximaData: '2026-09-01',
    ativa: true,
  },
  {
    id: 'PREV-007',
    maquinaId: 'MAQ-005',
    maquinaNome: 'Embaladora a Vácuo',
    setor: 'Açougue',
    lojaId: 'loja-1',
    descricao: 'Verificação do sistema de vácuo e troca do anel de vedação.',
    intervaloDias: 30,
    proximaData: '2026-08-01',
    ativa: true,
  },
]
