import type { OrdemServico } from '../tipos/ordemServico'

export const ORDENS_SERVICO_MOCK: OrdemServico[] = [
  {
    id: 1,
    solicitacaoId: 2,
    maquinaNome: 'Câmara Fria de Carnes',
    maquinaCodigo: 'MAQ-004',
    descricao: 'Câmara não está mantendo a temperatura mínima exigida.',
    setor: 'Açougue',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Aberta',
    dataAbertura: '2026-07-31T09:10:00',
  },
  {
    id: 2,
    solicitacaoId: 5,
    maquinaNome: 'Serra Fita para Carnes',
    maquinaCodigo: 'MAQ-003',
    descricao: 'Lâmina desalinhada causando corte irregular.',
    setor: 'Açougue',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Média',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Pausada',
    dataAbertura: '2026-07-28T13:40:00',
    motivoPausa: 'Aguardando chegada da lâmina de reposição.',
  },
  {
    id: 3,
    solicitacaoId: 16,
    maquinaNome: 'Forno Industrial de Pão',
    maquinaCodigo: 'MAQ-001',
    descricao: 'Alarme de sobreaquecimento disparando sem motivo aparente.',
    setor: 'Padaria',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Baixa',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Concluída',
    dataAbertura: '2026-07-20T08:30:00',
    dataInicio: '2026-07-20T09:00:00',
    dataFim: '2026-07-20T10:30:00',
    horasTrabalhadas: 1.5,
    custoHoraTecnico: 67.5,
    custoManutencao: 35,
    defeitoConstatado:
      'Sensor de temperatura do forno descalibrado, disparando o alarme de sobreaquecimento indevidamente.',
    causaRaiz: 'Sensor sem calibração periódica, gerando leitura incorreta da temperatura interna.',
    solucao: 'Recalibração do sensor de temperatura e teste de ciclo completo do forno.',
  },
  {
    id: 4,
    solicitacaoId: 6,
    maquinaNome: 'Balança Eletrônica de Pesagem',
    maquinaCodigo: 'MAQ-007',
    descricao: 'Leitura de peso divergente entre pesagens.',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Baixa',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Aberta',
    dataAbertura: '2026-08-01T10:05:00',
  },
  {
    id: 5,
    solicitacaoId: 9,
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    descricao: 'Compressor apresentando falha intermitente.',
    setor: 'Estoque',
    lojaId: 'loja-2',
    solicitante: 'Carlos',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Pausada',
    dataAbertura: '2026-07-25T15:20:00',
    motivoPausa: 'Aguardando técnico especializado em compressores.',
  },
  {
    id: 6,
    solicitacaoId: 18,
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    descricao: 'Ruído excessivo no compressor do balcão.',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    solicitante: 'Carlos',
    urgencia: 'Média',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Concluída',
    dataAbertura: '2026-07-15T11:00:00',
    dataInicio: '2026-07-15T11:30:00',
    dataFim: '2026-07-15T13:00:00',
    horasTrabalhadas: 1.5,
    custoHoraTecnico: 75,
    defeitoConstatado: 'Compressor com rolamento desgastado, gerando ruído excessivo durante o funcionamento.',
    causaRaiz: 'Falta de lubrificação periódica do rolamento do compressor.',
    solucao: 'Lubrificação do rolamento e ajuste da fixação do compressor no gabinete.',
  },
  {
    id: 7,
    solicitacaoId: 11,
    maquinaNome: 'Sistema de Refrigeração de Bebidas',
    maquinaCodigo: 'MAQ-014',
    descricao: 'Bebidas não estão gelando adequadamente.',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
    solicitante: 'Marina',
    urgencia: 'Média',
    tecnicoId: 'tecnico-3',
    statusExecucao: 'Aberta',
    dataAbertura: '2026-07-30T14:15:00',
  },
  {
    id: 8,
    solicitacaoId: 14,
    maquinaNome: 'Empilhadeira Elétrica',
    maquinaCodigo: 'MAQ-013',
    descricao: 'Bateria não segura carga por mais de 2 horas.',
    setor: 'Estoque',
    lojaId: 'loja-2',
    solicitante: 'Marina',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-3',
    statusExecucao: 'Concluída',
    dataAbertura: '2026-07-10T09:45:00',
    dataInicio: '2026-07-10T10:00:00',
    dataFim: '2026-07-10T11:30:00',
    horasTrabalhadas: 1.5,
    custoHoraTecnico: 60,
    defeitoConstatado: 'Células da bateria com capacidade reduzida por desgaste.',
    causaRaiz: 'Bateria próxima do fim da vida útil, sem substituição preventiva.',
    solucao: 'Recondicionamento da bateria e recomendação de substituição em até 3 meses.',
  },
  {
    id: 9,
    solicitacaoId: 12,
    maquinaNome: 'Balcão Refrigerado de Peixaria',
    maquinaCodigo: 'MAQ-008',
    descricao: 'Gelo derretendo rápido demais, produto exposto.',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Aberta',
    dataAbertura: '2026-08-02T08:20:00',
  },
  {
    id: 10,
    solicitacaoId: 17,
    maquinaNome: 'Câmara Fria de Hortifruti',
    maquinaCodigo: 'MAQ-006',
    descricao: 'Painel de controle travando ao configurar a temperatura.',
    setor: 'Hortifruti',
    lojaId: 'loja-1',
    solicitante: 'Marina',
    urgencia: 'Média',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Em Andamento',
    dataAbertura: '2026-07-29T09:00:00',
    dataInicio: '2026-08-01T13:30:00',
    sessaoAtualInicio: '2026-08-01T13:30:00',
  },
  {
    id: 11,
    solicitacaoId: 3,
    maquinaNome: 'Masseira Industrial',
    maquinaCodigo: 'MAQ-002',
    descricao: 'Motor com ruído excessivo durante o amassamento.',
    setor: 'Padaria',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Média',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Pausada',
    dataAbertura: '2026-07-27T10:15:00',
    statusAntesDaPausa: 'Em Andamento',
    dataInicio: '2026-07-27T14:00:00',
    horasTrabalhadasAcumuladas: 1.5,
    motivoPausa: 'Aguardando autorização do gestor para compra do rolamento do motor.',
  },
  {
    id: 12,
    solicitacaoId: 13,
    maquinaNome: 'Máquina de Gelo em Escamas',
    maquinaCodigo: 'MAQ-009',
    descricao: 'Produção de gelo abaixo do volume necessário.',
    setor: 'Peixaria',
    lojaId: 'loja-1',
    solicitante: 'Carlos',
    urgencia: 'Baixa',
    tecnicoId: 'tecnico-1',
    statusExecucao: 'Concluída',
    dataAbertura: '2026-07-18T09:30:00',
    dataInicio: '2026-07-18T13:00:00',
    dataFim: '2026-07-18T15:30:00',
    horasTrabalhadas: 2.5,
    custoHoraTecnico: 112.5,
    custoManutencao: 30,
    defeitoConstatado: 'Válvula de entrada de água parcialmente obstruída por incrustação de calcário.',
    causaRaiz: 'Falta de limpeza periódica do filtro de entrada de água da máquina.',
    solucao: 'Limpeza completa da válvula e do filtro, com orientação de manutenção preventiva mensal.',
  },
  {
    id: 13,
    solicitacaoId: 7,
    maquinaNome: 'Embaladora a Vácuo',
    maquinaCodigo: 'MAQ-005',
    descricao: 'Selagem das embalagens não está vedando corretamente.',
    setor: 'Açougue',
    lojaId: 'loja-1',
    solicitante: 'Marina',
    urgencia: 'Média',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Aberta',
    dataAbertura: '2026-08-02T11:10:00',
  },
  {
    id: 14,
    solicitacaoId: 10,
    maquinaNome: 'Fatiadora de Frios',
    maquinaCodigo: 'MAQ-011',
    descricao: 'Lâmina não corta uniformemente, deixando fatias grossas.',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    solicitante: 'Carlos',
    urgencia: 'Baixa',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Em Andamento',
    dataAbertura: '2026-07-30T09:40:00',
    dataInicio: '2026-08-01T08:00:00',
    sessaoAtualInicio: '2026-08-01T08:00:00',
  },
  {
    id: 15,
    solicitacaoId: 1,
    maquinaNome: 'Forno Industrial de Pão',
    maquinaCodigo: 'MAQ-001',
    descricao: 'Painel eletrônico piscando e desligando sozinho durante o uso.',
    setor: 'Padaria',
    lojaId: 'loja-1',
    solicitante: 'Eduardo',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Pausada',
    dataAbertura: '2026-07-26T07:50:00',
    statusAntesDaPausa: 'Em Andamento',
    dataInicio: '2026-07-26T13:00:00',
    horasTrabalhadasAcumuladas: 2,
    motivoPausa: 'Aguardando técnico eletricista para revisar a placa do painel.',
  },
  {
    id: 16,
    solicitacaoId: 209,
    maquinaNome: 'Câmara Fria de Estoque',
    maquinaCodigo: 'MAQ-012',
    descricao: 'Vedação da porta da câmara comprometida, perdendo refrigeração.',
    setor: 'Estoque',
    lojaId: 'loja-2',
    solicitante: 'Carlos',
    urgencia: 'Média',
    tecnicoId: 'tecnico-2',
    statusExecucao: 'Concluída',
    dataAbertura: '2026-07-14T08:00:00',
    dataInicio: '2026-07-14T09:30:00',
    dataFim: '2026-07-14T11:45:00',
    horasTrabalhadas: 2.25,
    custoHoraTecnico: 112.5,
    custoManutencao: 45,
    defeitoConstatado: 'Borracha de vedação da porta ressecada e rasgada em dois pontos.',
    causaRaiz: 'Desgaste natural da borracha por tempo de uso, sem substituição preventiva.',
    solucao: 'Substituição completa da borracha de vedação da porta.',
  },
  {
    id: 17,
    solicitacaoId: 210,
    maquinaNome: 'Balcão Refrigerado de Frios',
    maquinaCodigo: 'MAQ-010',
    descricao: 'Motor do balcão emitindo cheiro de queimado.',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    solicitante: 'Carlos',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-3',
    statusExecucao: 'Aberta',
    dataAbertura: '2026-08-02T15:00:00',
  },
  {
    id: 18,
    solicitacaoId: 211,
    maquinaNome: 'Empilhadeira Elétrica',
    maquinaCodigo: 'MAQ-013',
    descricao: 'Empilhadeira apresentando folga excessiva no garfo de elevação.',
    setor: 'Estoque',
    lojaId: 'loja-2',
    solicitante: 'Marina',
    urgencia: 'Média',
    tecnicoId: 'tecnico-3',
    statusExecucao: 'Em Andamento',
    dataAbertura: '2026-07-31T16:10:00',
    dataInicio: '2026-08-01T09:15:00',
    sessaoAtualInicio: '2026-08-01T09:15:00',
  },
  {
    id: 19,
    solicitacaoId: 15,
    maquinaNome: 'Ar Condicionado Central do Salão',
    maquinaCodigo: 'MAQ-015',
    descricao: 'Climatização insuficiente no salão de vendas.',
    setor: 'Frente de Loja',
    lojaId: 'loja-3',
    solicitante: 'Carlos',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-3',
    statusExecucao: 'Pausada',
    dataAbertura: '2026-07-23T11:35:00',
    statusAntesDaPausa: 'Aberta',
    motivoPausa: 'Aguardando peça de reposição do compressor do ar-condicionado.',
  },
  {
    id: 20,
    solicitacaoId: 212,
    maquinaNome: 'Fatiadora de Frios',
    maquinaCodigo: 'MAQ-011',
    descricao: 'Lâmina soltando durante o corte, risco de segurança.',
    setor: 'Frios e Laticínios',
    lojaId: 'loja-2',
    solicitante: 'Carlos',
    urgencia: 'Alta',
    tecnicoId: 'tecnico-3',
    statusExecucao: 'Concluída',
    dataAbertura: '2026-07-05T08:30:00',
    dataInicio: '2026-07-05T09:00:00',
    dataFim: '2026-07-05T10:15:00',
    horasTrabalhadas: 1.25,
    custoHoraTecnico: 50,
    defeitoConstatado: 'Trava de fixação da lâmina quebrada.',
    causaRaiz: 'Fadiga do material da trava por uso intenso sem manutenção preventiva.',
    solucao: 'Substituição da trava de fixação da lâmina e reaperto geral do conjunto.',
  },
]
