import type { Usuario } from '../tipos/usuario'

export const USUARIOS_MOCK: Usuario[] = [
  {
    id: 'usuario-1',
    nome: 'Eduardo',
    email: 'eduardo@cooprata.com.br',
    role: 'solicitante',
    lojasIds: ['loja-1'],
    setores: ['Padaria'],
    acessoTotalSetores: false,
  },
  {
    id: 'usuario-2',
    nome: 'Marina',
    email: 'marina@cooprata.com.br',
    role: 'solicitante',
    lojasIds: ['loja-2'],
    setores: ['Frios e Laticínios'],
    acessoTotalSetores: false,
  },
  {
    id: 'usuario-3',
    nome: 'Carlos',
    email: 'carlos@cooprata.com.br',
    role: 'solicitante',
    lojasIds: ['loja-2'],
    setores: ['Estoque'],
    acessoTotalSetores: false,
  },
  {
    id: 'usuario-4',
    nome: 'Ronald',
    email: 'ronald@cooprata.com.br',
    role: 'solicitante',
    lojasIds: ['loja-1'],
    setores: ['Açougue'],
    acessoTotalSetores: false,
  },
  {
    id: 'usuario-5',
    nome: 'Gestor Loja 1 - Padaria/Açougue',
    email: 'gestor1@cooprata.com.br',
    role: 'gestor',
    lojasIds: ['loja-1'],
    setores: ['Padaria', 'Açougue'],
    acessoTotalSetores: false,
  },
  {
    id: 'usuario-6',
    nome: 'Gestor Loja 1 - Hortifruti/Peixaria',
    email: 'gestor2@cooprata.com.br',
    role: 'gestor',
    lojasIds: ['loja-1'],
    setores: ['Hortifruti', 'Peixaria'],
    acessoTotalSetores: false,
  },
  {
    id: 'usuario-7',
    nome: 'Gestor Regional',
    email: 'regional@cooprata.com.br',
    role: 'gestor',
    lojasIds: ['loja-2', 'loja-3'],
    setores: [],
    acessoTotalSetores: true,
  },
  {
    id: 'usuario-8',
    nome: 'Administrador do Sistema',
    email: 'admin@cooprata.com.br',
    role: 'administrador',
    lojasIds: [],
    setores: [],
    acessoTotalSetores: true,
  },
]
